### ISSUE TITLE
Unavailable or private video

### ISSUE THREAD

**Issue by Gengzigang** [roudimit/MUSIC_dataset#2]
@roudimit Hi, The dataset provided in the json contains only the IDs of Youtube videos. I downloaded them but I found that many videos (43/685) is not available now, such as "flute 3wPouBFa9U0",  
"flute yaWxyD4zFKE". Could you please check this issue?
Thanks

**Comment by roudimit** [comment]
Hi,

Sorry for the late reply. I don't think there is anything we can do about that. For your research, you could train and test using whatever videos you were able to download and make a note in your paper. You could also check out some other new audio-visual datasets, such as this one: https://github.com/JuanFMontesinos/Solos.

I hope that helps.
Best,
Andrew
