### ISSUE TITLE
video clips

### ISSUE THREAD

**Issue by jane-pyc** [roudimit/MUSIC_dataset#4]
Hi, could you upload your all video clips and their corresponding  audio clips?
I have tried several times to download them from youtube by my VPN, but it failed always.
Thank you very much.

**Comment by roudimit** [comment]
Hi, 

Thank you for your interest. I am part of a different research group now, so I do not have access to the video data. You could try contacting Chuang Gan (http://people.csail.mit.edu/ganchuang/) who is still affiliated with the lab that published this research. 

I hope that helps.
